### Update User Request

@id = 424282de-cd73-4fe1-b799-424ed0df04c0

PUT {{baseUrl}}/api/users/{{id}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "firstName": "Thiago",
  "lastName": "Rodrigues",
  "email": "thiago@gmail.com",
  "password": "NewPassword123!"
}